### ISSUE TITLE
Feature request: bitcoin mining block list

### ISSUE THREAD

**Issue by JeffMelton** [austinheap/sophos-xg-block-lists#1]
See https://github.com/hoshsadiq/adblock-nocoin-list.

Thanks for doing this, by the way. Really helpful. 👍 🎉

**Comment by austinheap** [comment]
More than happy to. See commit https://github.com/austinheap/sophos-xg-block-lists/commit/8d9f484534b84488d3862b6740bb7fa540a794bf: https://github.com/austinheap/sophos-xg-block-lists/blob/master/nocoin.txt

Glad it's helpful! 😁
