### ISSUE TITLE
False Positive report on our domain ip2location.com in your list

### ISSUE THREAD

**Issue by ip2location-com** [austinheap/sophos-xg-block-lists#2]
Hi Austin Heap, recently when we viewed your block lists, we noticed that our domain ip2location.com was listed in easyprivacy.txt and adguard.txt. It is wrong because the IP2Location is a geolocation look up database that can be used to reverse translate IP address to the geolocation information such as country and city. We have contacted the source to remove our domain from their list, and now we would like you to update your list to remove our domain from your list. Thank You.

**Comment by austinheap** [comment]
Hi @ip2location -- once the upstream lists remove your domain (EasyPrivacy and AdGuard, in this case) it will automatically get removed from the block lists in this repo within 24 hours.
